### ISSUE TITLE
"theme_info" section is blank

### ISSUE THREAD

**Issue by ForrestHolt** [Kajabi/theme-cornerstone-page#3]
Could be by design by might be nice to have some dummy text
<img width="1164" alt="cornerstone - theme info 1" src="https://user-images.githubusercontent.com/17749903/53593940-a8621980-3b4e-11e9-8d3d-f1fb609fc913.png">
In section
<img width="1165" alt="cornerstone - theme info 2" src="https://user-images.githubusercontent.com/17749903/53593956-adbf6400-3b4e-11e9-9c64-b11fc66fcded.png">

**Comment by cmcfadzean** [comment]
This is going to be something moving forward that will show in another area and not show black in the editor.
