### ISSUE TITLE
Padding when Image is before/on top of Text

### ISSUE THREAD

**Issue by ForrestHolt** [Kajabi/theme-cornerstone-page#4]
![cornerstone - image above text](https://user-images.githubusercontent.com/17749903/53594080-ef500f00-3b4e-11e9-8bc0-7081df478f41.png)
The opposite looks good:
![cornerstone - image below text](https://user-images.githubusercontent.com/17749903/53594090-f4ad5980-3b4e-11e9-9521-48d56461f49a.png)

**Comment by cmcfadzean** [comment]
Resolved
