### ISSUE TITLE
Link formatting in Header and footer on mobile

### ISSUE THREAD

**Issue by ForrestHolt** [Kajabi/theme-cornerstone-page#5]
Could be by design since its supposed to be very simple but wanted to make sure
![cornerstone - header menu formatting](https://user-images.githubusercontent.com/17749903/53594203-36d69b00-3b4f-11e9-8095-1f356c7d053a.png)
![cornerstone - footer menu formatting](https://user-images.githubusercontent.com/17749903/53594205-3807c800-3b4f-11e9-99ba-de6203090336.png)

**Comment by cmcfadzean** [comment]
This is ok as the developer will do their own styles for these sections.
