### ISSUE TITLE
Fonts arent working in IE

### ISSUE THREAD

**Issue by ForrestHolt** [Kajabi/theme-cornerstone-page#6]
Font settings
<img width="1513" alt="screen shot 2019-02-28 at 1 38 33 pm" src="https://user-images.githubusercontent.com/17749903/53600376-46a9ab80-3b5e-11e9-83f9-b8f9b5ca2071.png">
Cornerstone via IE
![cornerstone ie fonts](https://user-images.githubusercontent.com/17749903/53600876-8ae97b80-3b5f-11e9-9130-d8cf6eda046f.PNG)

Same fonts in Premier via IE
![premier ie fonts](https://user-images.githubusercontent.com/17749903/53600882-8e7d0280-3b5f-11e9-9b94-945c61e0eb58.PNG)

**Comment by cmcfadzean** [comment]
Resolved
